return {
	["menu"] = {
		["MainText"] = "GUESS THE CAR\nBY PHOTO",
		["btn_play_text"] = "PLAY",
		["btn_leaderboard_text"] = "LEADERBOARD",
		["btn_settings_text"] = "SETTINGS",
		["btn_yes_text"] = "Yes",
		["btn_no_text"] = "No",
		["title"] = "Bonus for watching ad",
		["title2"] = "Do you want to get 30 coins?",
		["available"] = "Available",
	},
	["categories"] = {
		["txt_categories_title"] = "SELECT CATEGORY",
		["EasyCatText"] = "EASY",
		["MediumCatText1"] = "MEDIUM",
		["HardCatText1"] = "HARD",
		["levels_text"] = "LEVELS",
		["stars_text"] = "STARS",
	},
	["levels"] = {
		["txt_levels_title"] = "SELECT LEVEL",
	},
	["result"] = {
		["txt_result_errors1"] = "Errors: ",
		["txt_result_time1"] = "Time: ",
		["txt_result_next"] = "NEXT LEVEL",
		["exit_result_text"] = "MAIN MENU",
		["result_next_win"]  = "NEXT LEVEL",
		["result_next_lose"] = "TRY AGAIN",
		["title_result2"] = "get 2x?"
	},
	["settings"] = {
		["TextSettings"] = "SETTINGS",
		["MusicTextSett"] = "Music",
		["SoundsTextSett"] = "Sound effects",
		["SoundsTextSett1"] = "Language",
		["on_music_text"] = "On",
		["off_music_text"] = "Off",
		["on_sound_text"] = "On",
		["off_sound_text"] = "Off",
		["lang_ru"] = "Rus",
		["lang_eng"] = "Eng",
	},
	["leaderboard"] = {
		["LeaderboardText"] = "LEADERBOARD",
		["name_text_leaderboard"] = "Name",
		["money_text_leaderboard"] = "Coins",
	},

	["gameplay"] = {
		["title_gameplay"] = "What car is in the photo?",
		["txt_hint_skip"] = "Skip",
		["hint50_or_text"] = "or",
		["hint_or_text"] = "or",
		["btn_yes_text_gameplay"] = "Yes",
		["btn_no_text_gameplay"] = "No",
		["ad_block_title"] = "You don't have enough coins",
		["txt_ad_block_message"] = "Use for free\nby watching an ad?",
		["top_text"] = "PAUSE",
		["btn_continue_text"] = "Continue",
		["btn_settings_text"] = "Settings",
		["btn_main_menu_text"] = "Main menu",
	}
}