return {
	["menu"] = {
		["MainText"] = "УГАДАЙ МАШИНУ\nПО ФОТО",
		["btn_play_text"] = "ИГРАТЬ",
		["btn_leaderboard_text"] = "ТАБЛИЦА ЛИДЕРОВ",
		["btn_settings_text"] = "НАСТРОЙКИ",
		["btn_yes_text"] = "Да",
		["btn_no_text"] = "Нет",
		["title"] = "Бонус за просмотр рекламы",
		["title2"] = "Хотите получить 30 монет?",
		["available"] = "Доступно",
	},
	["categories"] = {
		["txt_categories_title"] = "ВЫБОР КАТЕГОРИИ",
		["EasyCatText"] = "ЛЁГКАЯ",
		["MediumCatText1"] = "СРЕДНЯЯ",
		["HardCatText1"] = "СЛОЖНАЯ",
		["levels_text"] = "УРОВНИ",
		["stars_text"] = "ЗВЁЗДЫ",
	},
	["levels"] = {
		["txt_levels_title"] = "ВЫБОР УРОВНЯ",
	},
	["result"] = {
		["txt_result_errors1"] = "Ошибки: ",
		["txt_result_time1"] = "Время: ",
		["txt_result_next"] = "СЛЕДУЮЩИЙ УРОВЕНЬ",
		["exit_result_text"] = "ГЛАВНОЕ МЕНЮ",
		["result_next_win"]  = "СЛЕДУЮЩИЙ УРОВЕНЬ",
		["result_next_lose"] = "ПРОЙТИ ЕЩЕ РАЗ",
		["title_result1"] = "Бонус за просмотр рекламы",
		["title_result2"] = "Хотите удвоить награду?",
		["btn_no_text1"] = "Нет",
		["btn_yes_text1"] = "Да",
		["result_win"] = "УРОВЕНЬ ПРОЙДЕН!",
		["result_lose"] = "ПРОИГРЫШ",
		["result_coins"] = "Монет: +",
	},
	["settings"] = {
		["TextSettings"] = "НАСТРОЙКИ",
		["MusicTextSett"] = "Музыка",
		["SoundsTextSett"] = "Звуковые эффекты",
		["SoundsTextSett1"] = "Язык",
		["on_music_text"] = "Вкл",
		["off_music_text"] = "Выкл",
		["on_sound_text"] = "Вкл",
		["off_sound_text"] = "Выкл",
		["lang_ru"] = "Рус",
		["lang_eng"] = "Англ",
	},
	["leaderboard"] = {
		["LeaderboardText"] = "ТАБЛИЦА ЛИДЕРОВ",
		["name_text_leaderboard"] = "Имя",
		["money_text_leaderboard"] = "Монеты",
	},

	["gameplay"] = {
		["title_gameplay"] = "Что за машина на фото?",
		["txt_hint_skip"] = "Пропуск",
		["hint50_or_text"] = "или",
		["hint_or_text"] = "или",
		["btn_yes_text_gameplay"] = "Да",
		["btn_no_text_gameplay"] = "Нет",
		["ad_block_title"] = "У вас не хватает монет",
		["txt_ad_block_message"] = "Использовать бесплатно\nза просмотр рекламы?",
		["top_text"] = "ПАУЗА",
		["btn_continue_text"] = "Продолжить",
		["btn_settings_text"] = "Настройки",
		["btn_main_menu_text"] = "Главное меню",
	}
}