local M = {}

M.categories = {
	easy = {
		level_1 = {
			{ id = "easy_01.1", image = "images/easy_01.1.jpg", name = "Toyota Camry" },
			{ id = "easy_02.1", image = "images/easy_02.1.jpg", name = "Hyundai Solaris" },
			{ id = "easy_03.1", image = "images/easy_03.1.jpg", name = "Kia Rio" },
			{ id = "easy_04.1", image = "images/easy_04.1.jpg", name = "Volkswagen Polo" },
			{ id = "easy_05.1", image = "images/easy_05.1.jpg", name = "Renault Logan" },
			{ id = "easy_06.1", image = "images/easy_06.1.jpg", name = "Lada Granta" },
			{ id = "easy_07.1", image = "images/easy_07.1.jpg", name = "Skoda Octavia" },
			{ id = "easy_08.1", image = "images/easy_08.1.jpg", name = "Ford Focus" },
			{ id = "easy_09.1", image = "images/easy_09.1.jpg", name = "LADA 2107" },
			{ id = "easy_10.1", image = "images/easy_10.1.jpg", name = "Nissan Qashqai" },
			{ id = "easy_11.1", image = "images/easy_11.1.jpg", name = "BMW X5" },
			{ id = "easy_12.1", image = "images/easy_12.1.jpg", name = "Mercedes-Benz E-Class" },
			{ id = "easy_13.1", image = "images/easy_13.1.jpg", name = "Audi A4" },
			{ id = "easy_14.1", image = "images/easy_14.1.jpg", name = "Toyota Land Cruiser Prado" },
			{ id = "easy_15.1", image = "images/easy_15.1.jpg", name = "Mitsubishi Lancer" },
		},
		level_2 = {
			{ id = "easy_01.2", image = "images/easy_01.2.jpg", name = "Mazda 6" },
			{ id = "easy_02.2", image = "images/easy_02.2.jpg", name = "Honda Civic" },
			{ id = "easy_03.2", image = "images/easy_03.2.jpg", name = "Lexus RX" },
			{ id = "easy_04.2", image = "images/easy_04.2.jpg", name = "Porsche Cayenne" },
			{ id = "easy_05.2", image = "images/easy_05.2.jpg", name = "Daewoo Matiz" },
			{ id = "easy_06.2", image = "images/easy_06.2.jpg", name = "Lada Niva Legend" },
			{ id = "easy_07.2", image = "images/easy_07.2.jpg", name = "Volkswagen Tiguan" },
			{ id = "easy_08.2", image = "images/easy_08.2.jpg", name = "Kia Sportage" },
			{ id = "easy_09.2", image = "images/easy_09.2.jpg", name = "Hyundai Creta" },
			{ id = "easy_10.2", image = "images/easy_10.2.jpg", name = "Renault Duster" },
			{ id = "easy_11.2", image = "images/easy_11.2.jpg", name = "Nissan Juke" },
			{ id = "easy_12.2", image = "images/easy_12.2.jpg", name = "Subaru Forester" },
			{ id = "easy_13.2", image = "images/easy_13.2.jpg", name = "Opel Astra" },
			{ id = "easy_14.2", image = "images/easy_14.2.jpg", name = "Peugeot 308" },
			{ id = "easy_15.2", image = "images/easy_15.2.jpg", name = "Citroen C4" },
		},
		level_3 = {
			{ id = "easy_01.3", image = "images/easy_01.3.jpg", name = "Toyota RAV4" },
			{ id = "easy_02.3", image = "images/easy_02.3.jpg", name = "Mitsubishi Outlander" },
			{ id = "easy_03.3", image = "images/easy_03.3.jpg", name = "Mazda CX-5" },
			{ id = "easy_04.3", image = "images/easy_04.3.jpg", name = "Suzuki Vitara" },
			{ id = "easy_05.3", image = "images/easy_05.3.jpg", name = "Chevrolet Niva" },
			{ id = "easy_06.3", image = "images/easy_06.3.jpg", name = "Geely Coolray" },
			{ id = "easy_07.3", image = "images/easy_07.3.jpg", name = "Haval Jolion" },
			{ id = "easy_08.3", image = "images/easy_08.3.jpg", name = "Chery Tiggo 7" },
			{ id = "easy_09.3", image = "images/easy_09.3.jpg", name = "Lifan Solano" },
			{ id = "easy_10.3", image = "images/easy_10.3.jpg", name = "UAZ Patriot" },
			{ id = "easy_11.3", image = "images/easy_11.3.jpg", name = "MINI Cooper" },
			{ id = "easy_12.3", image = "images/easy_12.3.jpg", name = "Chevrolet Cruze" },
			{ id = "easy_13.3", image = "images/easy_13.3.jpg", name = "Fiat 500" },
			{ id = "easy_14.3", image = "images/easy_14.3.jpg", name = "Volkswagen Beetle" },
			{ id = "easy_15.3", image = "images/easy_15.3.jpg", name = "Ford Mustang" },
		},
	},
	medium = {
		level_1 = {
			{ id = "medium_01.1", image = "images/medium_01.1.jpg", name = "Volvo S60" },
			{ id = "medium_02.1", image = "images/medium_02.1.jpg", name = "Saab 9-3" },
			{ id = "medium_03.1", image = "images/medium_03.1.jpg", name = "Alfa Romeo 159" },
			{ id = "medium_04.1", image = "images/medium_04.1.jpg", name = "Jaguar XF" },
			{ id = "medium_05.1", image = "images/medium_05.1.jpg", name = "Chrysler 300C" },
			{ id = "medium_06.1", image = "images/medium_06.1.jpg", name = "Cadillac CTS" },
			{ id = "medium_07.1", image = "images/medium_07.1.jpg", name = "Infiniti FX35" },
			{ id = "medium_08.1", image = "images/medium_08.1.jpg", name = "Acura MDX" },
			{ id = "medium_09.1", image = "images/medium_09.1.jpg", name = "Genesis G80" },
			{ id = "medium_10.1", image = "images/medium_10.1.jpg", name = "Rover 75" },
			{ id = "medium_11.1", image = "images/medium_11.1.jpg", name = "Smart Fortwo" },
			{ id = "medium_12.1", image = "images/medium_12.1.jpg", name = "Seat Leon" },
			{ id = "medium_13.1", image = "images/medium_13.1.jpg", name = "Skoda Yeti" },
			{ id = "medium_14.1", image = "images/medium_14.1.jpg", name = "Tesla Cybertruck" },
			{ id = "medium_15.1", image = "images/medium_15.1.jpg", name = "Citroen C6" },
		},
		level_2 = {
			{ id = "medium_01.2", image = "images/medium_01.2.jpg", name = "Tesla Model X" },
			{ id = "medium_02.2", image = "images/medium_02.2.jpg", name = "Honda Element" },
			{ id = "medium_03.2", image = "images/medium_03.2.jpg", name = "Dodge Challenger" },
			{ id = "medium_04.2", image = "images/medium_04.2.jpg", name = "Nissan Cube" },
			{ id = "medium_05.2", image = "images/medium_05.2.jpg", name = "Scion xB" },
			{ id = "medium_06.2", image = "images/medium_06.2.jpg", name = "GAZ-24 Volga" },
			{ id = "medium_07.2", image = "images/medium_07.2.jpg", name = "VAZ-2101 Zhiguli" },
			{ id = "medium_08.2", image = "images/medium_08.2.jpg", name = "Moskvich-412" },
			{ id = "medium_09.2", image = "images/medium_09.2.jpg", name = "ZAZ-968 Zaporozhets" },
			{ id = "medium_10.2", image = "images/medium_10.2.jpg", name = "Mercedes-Benz W123" },
			{ id = "medium_11.2", image = "images/medium_11.2.jpg", name = "BMW E30" },
			{ id = "medium_12.2", image = "images/medium_12.2.jpg", name = "Audi 80" },
			{ id = "medium_13.2", image = "images/medium_13.2.jpg", name = "Volkswagen Golf Mk2" },
			{ id = "medium_14.2", image = "images/medium_14.2.jpg", name = "Volvo 240" },
			{ id = "medium_15.2", image = "images/medium_15.2.jpg", name = "Ford Sierra" },
		},
		level_3 = {
			{ id = "medium_01.3", image = "images/medium_01.3.jpg", name = "Subaru Impreza WRX STI" },
			{ id = "medium_02.3", image = "images/medium_02.3.jpg", name = "Mitsubishi Lancer Evolution" },
			{ id = "medium_03.3", image = "images/medium_03.3.jpg", name = "Toyota Supra A80" },
			{ id = "medium_04.3", image = "images/medium_04.3.jpg", name = "Nissan Skyline R34" },
			{ id = "medium_05.3", image = "images/medium_05.3.jpg", name = "Mazda RX-7" },
			{ id = "medium_06.3", image = "images/medium_06.3.jpg", name = "Honda S2000" },
			{ id = "medium_07.3", image = "images/medium_07.3.jpg", name = "Nissan 350Z" },
			{ id = "medium_08.3", image = "images/medium_08.3.jpg", name = "Audi TT" },
			{ id = "medium_09.3", image = "images/medium_09.3.jpg", name = "Porsche Boxster" },
			{ id = "medium_10.3", image = "images/medium_10.3.jpg", name = "BMW Z4" },
			{ id = "medium_11.3", image = "images/medium_11.3.jpg", name = "Hummer H2" },
			{ id = "medium_12.3", image = "images/medium_12.3.jpg", name = "Jeep Wrangler" },
			{ id = "medium_13.3", image = "images/medium_13.3.jpg", name = "Land Rover Defender" },
			{ id = "medium_14.3", image = "images/medium_14.3.jpg", name = "Toyota FJ Cruiser" },
			{ id = "medium_15.3", image = "images/medium_15.3.jpg", name = "Ford F-150" },
		},
	},
	hard = {
		level_1 = {
			{ id = "hard_01.1", image = "images/hard_01.1.jpg", name = "Bugatti Veyron" },
			{ id = "hard_02.1", image = "images/hard_02.1.jpg", name = "Ferrari LaFerrari" },
			{ id = "hard_03.1", image = "images/hard_03.1.jpg", name = "McLaren P1" },
			{ id = "hard_04.1", image = "images/hard_04.1.jpg", name = "Porsche 918 Spyder" },
			{ id = "hard_05.1", image = "images/hard_05.1.jpg", name = "Lamborghini Aventador" },
			{ id = "hard_06.1", image = "images/hard_06.1.jpg", name = "Pagani Huayra" },
			{ id = "hard_07.1", image = "images/hard_07.1.jpg", name = "Koenigsegg Agera" },
			{ id = "hard_08.1", image = "images/hard_08.1.jpg", name = "Aston Martin One-77" },
			{ id = "hard_09.1", image = "images/hard_09.1.jpg", name = "Noble M600" },
			{ id = "hard_10.1", image = "images/hard_10.1.jpg", name = "Zenvo ST1" },
			{ id = "hard_11.1", image = "images/hard_11.1.jpg", name = "Spyker C8" },
			{ id = "hard_12.1", image = "images/hard_12.1.jpg", name = "Vector M12" },
			{ id = "hard_13.1", image = "images/hard_13.1.jpg", name = "TVR Sagaris" },
			{ id = "hard_14.1", image = "images/hard_14.1.jpg", name = "Bristol Fighter" },
			{ id = "hard_15.1", image = "images/hard_15.1.jpg", name = "Gumpert Apollo" },
		},
		level_2 = {
			{ id = "hard_01.2", image = "images/hard_01.2.jpg", name = "Saleen S7" },
			{ id = "hard_02.2", image = "images/hard_02.2.jpg", name = "SSC Tuatara" },
			{ id = "hard_03.2", image = "images/hard_03.2.jpg", name = "Hennessey Venom GT" },
			{ id = "hard_04.2", image = "images/hard_04.2.jpg", name = "Rimac Nevera" },
			{ id = "hard_05.2", image = "images/hard_05.2.jpg", name = "NIO EP9" },
			{ id = "hard_06.2", image = "images/hard_06.2.jpg", name = "Plymouth Prowler" },
			{ id = "hard_07.2", image = "images/hard_07.2.jpg", name = "DeLorean DMC-12" },
			{ id = "hard_08.2", image = "images/hard_08.2.jpg", name = "Vector W8" },
			{ id = "hard_09.2", image = "images/hard_09.2.jpg", name = "Cizeta V16T" },
			{ id = "hard_10.2", image = "images/hard_10.2.jpg", name = "Isdera Imperator" },
			{ id = "hard_11.2", image = "images/hard_11.2.jpg", name = "Panther Solo" },
			{ id = "hard_12.2", image = "images/hard_12.2.jpg", name = "Mitsuoka Orochi" },
			{ id = "hard_13.2", image = "images/hard_13.2.jpg", name = "Tommykaira ZZ" },
			{ id = "hard_14.2", image = "images/hard_14.2.jpg", name = "Donkervoort D8" },
			{ id = "hard_15.2", image = "images/hard_15.2.jpg", name = "KTM X-Bow" },
		},
		level_3 = {
			{ id = "hard_01.3", image = "images/hard_01.3.jpg", name = "Tucker Torpedo" },
			{ id = "hard_02.3", image = "images/hard_02.3.jpg", name = "Bricklin SV-1" },
			{ id = "hard_03.3", image = "images/hard_03.3.jpg", name = "Studebaker Avanti" },
			{ id = "hard_04.3", image = "images/hard_04.3.jpg", name = "Jensen Interceptor" },
			{ id = "hard_05.3", image = "images/hard_05.3.jpg", name = "Iso Grifo" },
			{ id = "hard_06.3", image = "images/hard_06.3.jpg", name = "De Tomaso Pantera" },
			{ id = "hard_07.3", image = "images/hard_07.3.jpg", name = "Facel Vega Excellence" },
			{ id = "hard_08.3", image = "images/hard_08.3.jpg", name = "Monteverdi High Speed" },
			{ id = "hard_09.3", image = "images/hard_09.3.jpg", name = "Bizzarrini 5300 GT" },
			{ id = "hard_10.3", image = "images/hard_10.3.jpg", name = "Pegaso Z-102" },
			{ id = "hard_11.3", image = "images/hard_11.3.jpg", name = "Marussia B2" },
			{ id = "hard_12.3", image = "images/hard_12.3.jpg", name = "Lada Revolution" },
			{ id = "hard_13.3", image = "images/hard_13.3.jpg", name = "Rezvani Beast" },
			{ id = "hard_14.3", image = "images/hard_14.3.jpg", name = "W Motors Lykan HyperSport" },
			{ id = "hard_15.3", image = "images/hard_15.3.jpg", name = "Zenvo Aurora" },
		},
	},
}

return M

--[[
local data = {}

data.questions = {
	easy = {
		{ img = "car_toyota_camry",      correct = 1, answers = {"Toyota Camry", "Honda Accord", "Nissan Altima", "Hyundai Sonata"} },
		{ img = "car_hyundai_solaris",   correct = 2, answers = {"Kia Rio", "Hyundai Solaris", "Renault Logan", "Volkswagen Polo"} },
		{ img = "car_kia_rio",           correct = 3, answers = {"Hyundai Solaris", "Skoda Rapid", "Kia Rio", "Ford Fiesta"} },
		{ img = "car_vw_polo",           correct = 1, answers = {"Volkswagen Polo", "Skoda Fabia", "Seat Ibiza", "Audi A1"} },
		{ img = "car_renault_logan",     correct = 4, answers = {"Lada Granta", "Kia Rio", "Hyundai Solaris", "Renault Logan"} },
		{ img = "car_lada_granta",       correct = 2, answers = {"Lada Vesta", "Lada Granta", "Lada Priora", "Lada Kalina"} },
		{ img = "car_skoda_octavia",     correct = 1, answers = {"Skoda Octavia", "Volkswagen Golf", "Seat Leon", "Audi A3"} },
		{ img = "car_ford_focus",        correct = 3, answers = {"Opel Astra", "Chevrolet Cruze", "Ford Focus", "Mazda 3"} },
		{ img = "car_chevrolet_cruze",   correct = 2, answers = {"Ford Focus", "Chevrolet Cruze", "Opel Astra", "Toyota Corolla"} },
		{ img = "car_nissan_qashqai",    correct = 4, answers = {"Toyota RAV4", "Hyundai Tucson", "Kia Sportage", "Nissan Qashqai"} },
		{ img = "car_bmw_x5",           correct = 1, answers = {"BMW X5", "Mercedes GLE", "Audi Q7", "Volvo XC90"} },
		{ img = "car_mercedes_e",        correct = 3, answers = {"BMW 5 Series", "Audi A6", "Mercedes-Benz E-Class", "Lexus ES"} },
		{ img = "car_audi_a4",          correct = 2, answers = {"BMW 3 Series", "Audi A4", "Mercedes C-Class", "Volvo S60"} },
		{ img = "car_lc_prado",         correct = 4, answers = {"Mitsubishi Pajero", "Land Rover Discovery", "Nissan Patrol", "Toyota Land Cruiser Prado"} },
		{ img = "car_mitsubishi_lancer", correct = 1, answers = {"Mitsubishi Lancer", "Subaru Impreza", "Honda Civic", "Mazda 3"} },
	},
	medium = {},
	hard = {}
}

return data
]]