-- scripts/gameplay/gameplay.gui_script

local gameplay_manager = require("scripts.managers.gameplay_manager")

function init(self)
	gameplay_manager.init(self)
end

function on_message(self, message_id, message, sender)
	gameplay_manager.on_message(self, message_id, message)
end

function update(self, dt)
	gameplay_manager.update(self, dt)
end

function on_input(self, action_id, action)
	gameplay_manager.on_input(self, action_id, action)
end