local save_manager = require("scripts.save_manager")

function init(self)
	msg.post(".", "acquire_input_focus")

	msg.post(".", "acquire_input_focus")
	local save_data = save_manager.load()
	print("Монет в сохранении: " .. save_data.coins)
	gui.set_text(gui.get_node("txt_total_coins"), "$ " .. save_data.coins)
	
	self.sound_on = true
	self.buttons = {
		{ node = "btn_play",        target = "categories" },
		{ node = "btn_leaderboard", target = "leaderboard" },
		{ node = "btn_settings",    target = "settings" },
		{ node = "btn_easy",        target = "gameplay", difficulty = "easy" },
		{ node = "btn_medium",      target = "gameplay", difficulty = "medium" },
		{ node = "btn_hard",        target = "gameplay", difficulty = "hard" },
		{ node = "exit",        target = "menu" },
	}

	change_gui("menu")
	print("Menu init работает!")
end

function toggle_sound(self)
	self.sound_on = not self.sound_on

	if self.sound_on then
		msg.post("/music#sound", "play_sound")
		gui.set_text(gui.get_node("btn_sound_text"), "Музыка вкл")
	else
		msg.post("/music#sound", "stop_sound")
		gui.set_text(gui.get_node("btn_sound_text"), "Музыка офф")
	end
end

function change_gui(name)
	local screens = {"menu", "settings", "categories", "leaderboard", "result"}

	for _, screen_name in ipairs(screens) do
		local node = gui.get_node("screen_" .. screen_name)
		gui.set_enabled(node, screen_name == name)
	end
	
	local back_btn = gui.get_node("exit")
	gui.set_enabled(back_btn, name ~= "menu")
end

function on_message(self, message_id, message)
	if message_id == hash("show_result") then
		
		local save_data = save_manager.load()
		gui.set_text(gui.get_node("txt_total_coins"), "$ " .. save_data.coins)
		
		gui.set_text(gui.get_node("txt_result_title"), message.win and "Победа!" or "Поражение!")
		gui.set_text(gui.get_node("txt_result_coins"), "Монет: +" .. message.coins)
		gui.set_text(gui.get_node("txt_result_errors"), "Ошибок: " .. message.errors)

		local stars_text = ""
		for i = 1, 3 do
			stars_text = stars_text .. (i <= message.stars and "* " or "- ")
		end
		gui.set_text(gui.get_node("txt_result_stars"), stars_text)

		-- кнопки
		gui.set_text(gui.get_node("txt_result_next"), message.win and "Дальше" or "Заново")

		change_gui("result")
	end
end

function on_input(self, action_id, action)
	if action_id == hash("touch") and action.pressed then
		local sound_btn = gui.get_node("btn_sound")
		if gui.pick_node(sound_btn, action.x, action.y) then
			toggle_sound(self)
			return
		end
		
		for _, btn in ipairs(self.buttons) do
			local node = gui.get_node(btn.node)
			if gui.is_enabled(node, true) and gui.pick_node(node, action.x, action.y) then
				print(btn.node .. " нажато")

				if btn.target == "gameplay" then
					msg.post("/gameplay#gameplay", "enable")
					msg.post("/menu#menu", "disable")
					msg.post("/gameplay#gameplay", "start_game", { difficulty = btn.difficulty  })
				else
					change_gui(btn.target)
				end
				break
			end
		end

	end
end